version: "3.9"

services:


  redis:
    image: redis:7
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: face
      POSTGRES_PASSWORD: face
      POSTGRES_DB: face_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U face -d face_db"]
      interval: 5s
      timeout: 3s
      retries: 15
      start_period: 10s


  migrator:
    build:
      context: .
      dockerfile: shared/Dockerfile
    environment:
      DATABASE_URL: postgresql://face:face@postgres:5432/face_db
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"


  api:
    build:
      context: .
      dockerfile: services/api/Dockerfile
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://face:face@postgres:5432/face_db
      HR_API_BASE: "https://host.docker.internal:4050"
      HR_SSL_VERIFY: "false"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      postgres:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
    restart: unless-stopped


  producer:
    build:
      context: .
      dockerfile: services/producer/Dockerfile
    environment:
      DATABASE_URL: postgresql://face:face@postgres:5432/face_db
      REDIS_HOST: redis
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
    restart: unless-stopped


  worker:
    build:
      context: .
      dockerfile: services/worker/Dockerfile
    environment:
      DATABASE_URL: postgresql://face:face@postgres:5432/face_db
      REDIS_HOST: redis
      CROSSING_COOLDOWN_SECONDS: "60"
      HR_API_BASE: "https://host.docker.internal:4050"
      HR_SSL_VERIFY: "false"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
    restart: unless-stopped
    deploy:
      replicas: 2

volumes:
  pgdata:
