"""init

Revision ID: cf0719dc1cb7
Revises: 
Create Date: 2026-06-10 17:38:28.143720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf0719dc1cb7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('new_faces', sa.Integer(), nullable=True),
    sa.Column('known_faces', sa.Integer(), nullable=True),
    sa.Column('male', sa.Integer(), nullable=True),
    sa.Column('female', sa.Integer(), nullable=True),
    sa.Column('kids', sa.Integer(), nullable=True),
    sa.Column('teens', sa.Integer(), nullable=True),
    sa.Column('adults', sa.Integer(), nullable=True),
    sa.Column('middle', sa.Integer(), nullable=True),
    sa.Column('elderly', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_stats')
    # ### end Alembic commands ###
